<?php

namespace Modules\Task\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Modules\Task\Entities\Task;

class TaskTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $tasks = [
            [
                'task_number' => 'T-Y-M-S-RCH-RNUM1',
                'category_id' => 1,
                'title' => 'Task number 1',
                'description' => 'eiusmod tempor incididunt ut labore et dolore magna aliqua. Facilisi crauris in. Interdum consectetur libero id faucibus nisl.',
                'employer_id' => 1,
                'proof_request_ques' => 'Based on your input, get a random alpha numeric string. The random string generator creates a series of numbers ',
                'proof_request_screenShot' => 'nerate a 16 character output based on your input of numbers and upper and lower case letters.  Random strings can be unique. Used in computing, a random string generator can also be called a random character string generator. This is',
                'total_worker_limit' => '10',
                'cost_per_worker' => '1.00',
                'task_end_date' => '2023-11-10',
                'special_access' => 'true',
                'only_professional' => 'false',
                'daily_limit' => null,
                'task_cost' => '10.00',
                'other_cost' => '25.00',
                'total_cost' => '35.00',
                'publish_status' => 'Published',
            ],

            [
                'task_number' => 'T-Y-M-S-RCH-RNUM2',
                'category_id' => 2,
                'title' => 'Task number 2',
                'description' => 'Loremidunt ut labore et dolore magna aliqua Gravida rutrum quisque non tellus orci ac auctor augue.',
                'employer_id' => 2,
                'proof_request_ques' => 'mber of randomized strings are needed as they could be in stat',
                'proof_request_screenShot' => 'ossible applications for a random string generator co',
                'total_worker_limit' => '5',
                'cost_per_worker' => '5.00',
                'task_end_date' => '2023-12-10',
                'special_access' => 'false',
                'only_professional' => 'true',
                'daily_limit' => '3',
                'task_cost' => '25.00',
                'other_cost' => '40.00',
                'total_cost' => '65.00',
                'publish_status' => 'Published',
            ],

            [
                'task_number' => 'T-Y-M-S-RCH-RNUM3',
                'category_id' => 3,
                'title' => 'Task number 3',
                'description' => 'Lorem ipsum domagna fermentum iaculis eu non diam. Gravida arcu cibus ornare.',
                'employer_id' => 3,
                'proof_request_ques' => 'In statistical theory, randomization is an important principle with one possible application involving survey sampling.',
                'proof_request_screenShot' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et',
                'total_worker_limit' => '30',
                'cost_per_worker' => '2.166666667',
                'task_end_date' => '2023-10-28',
                'special_access' => 'true',
                'only_professional' => 'false',
                'daily_limit' => '4',
                'task_cost' => '65.00',
                'other_cost' => '76.00',
                'total_cost' => '141.00',
                'publish_status' => 'Published',
            ],

            [
                'task_number' => 'T-Y-M-S-RCH-RNUM4',
                'category_id' => 4,
                'title' => 'Task number 4',
                'description' => 'piscing elit, sed do eiusmodeo. Nisl rhoncus mattis  fac pretium.',
                'employer_id' => 4,
                'proof_request_ques' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et',
                'proof_request_screenShot' => 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci ve',
                'total_worker_limit' => '90',
                'cost_per_worker' => '1.5',
                'task_end_date' => '2023-05-05',
                'special_access' => 'true',
                'only_professional' => 'true',
                'daily_limit' => '46',
                'task_cost' => '135.00',
                'other_cost' => '56.00',
                'total_cost' => '191.00',
                'publish_status' => 'Published',
            ],

            [
                'task_number' => 'T-Y-M-S-RCH-RNUM5',
                'category_id' => 5,
                'title' => 'Task number 5',
                'description' => 'lit, sedet dolore magna aliqua. Nec tempor id eu nisl nunc. andit libero volutpat sed.',
                'employer_id' => 5,
                'proof_request_ques' => ' fermentum, augue at blandit d',
                'proof_request_screenShot' => ' vitae porttitor pretium. Maecenas id facilisis risu',
                'total_worker_limit' => '76',
                'cost_per_worker' => '14.05',
                'task_end_date' => '2024-08-02',
                'special_access' => 'true',
                'only_professional' => 'false',
                'daily_limit' => '14',
                'task_cost' => '1102.00',
                'other_cost' => '59.00',
                'total_cost' => '1161.00',
                'publish_status' => 'Published',
            ],

            [
                'task_number' => 'T-Y-M-S-RCH-RNUM6',
                'category_id' => 6,
                'title' => 'Task number 6',
                'description' => ' ut labore et dolore magna aliqua. Vel risus commods est pellentesque elit ullamcorper.',
                'employer_id' => 6,
                'proof_request_ques' => 'rem, nec luctus mi vehicula et. Aenean non enim tortor. Nullam imperdiet qua',
                'proof_request_screenShot' => ' elit faucibus non. Aliquam era',
                'total_worker_limit' => '23',
                'cost_per_worker' => '6.65',
                'task_end_date' => '2023-12-04',
                'special_access' => 'true',
                'only_professional' => 'false',
                'daily_limit' => '12',
                'task_cost' => '152.95',
                'other_cost' => '87.00',
                'total_cost' => '239.95',
                'publish_status' => 'Published',
            ],

            [
                'task_number' => 'T-Y-M-S-RCH-RNUM7',
                'category_id' => 7,
                'title' => 'Task number 7',
                'description' => ' incididunt ut labore et dolore magna aliqua. Gravida dictum fusce ut plassim enim.',
                'employer_id' => 7,
                'proof_request_ques' => 'cibus. Proin pulvinar efficitur aliquam. F',
                'proof_request_screenShot' => 'lis arcu. Proin non tempus sem. Nam molestie sapien sed e',
                'total_worker_limit' => '35',
                'cost_per_worker' => '76.23',
                'task_end_date' => '2025-12-14',
                'special_access' => 'true',
                'only_professional' => 'true',
                'daily_limit' => '32',
                'task_cost' => '2668.05',
                'other_cost' => '12.23',
                'total_cost' => '2680.28',
                'publish_status' => 'Published',
            ],
            [
                'task_number' => 'T-Y-M-S-RCH-RNUM8',
                'category_id' => 8,
                'title' => 'Task number 8',
                'description' => 'Lorepor incididunt ut labore et dolore magna aliqua. Elit pellentetus et.',
                'employer_id' => 8,
                'proof_request_ques' => ' potenti. Donec id mi mi. Do',
                'proof_request_screenShot' => 'it, quis placerat erat placerat convallis. Sed elei',
                'total_worker_limit' => '88',
                'cost_per_worker' => '76.67',
                'task_end_date' => '2024-12-11',
                'special_access' => 'false',
                'only_professional' => 'true',
                'daily_limit' => '71',
                'task_cost' => '6746.96',
                'other_cost' => '6.35',
                'total_cost' => '6753.31',
                'publish_status' => 'Published',
            ],
            [
                'task_number' => 'T-Y-M-S-RCH-RNUM9',
                'category_id' => 9,
                'title' => 'Task number 9',
                'description' => 'Lorem ips magna aliqua. Dolor sit amet consectetur adipiscing elit duis tristique.',
                'employer_id' => 9,
                'proof_request_ques' => '. Donec id mi mi. Do',
                'proof_request_screenShot' => ' dignissim tellus dignissim aliquet. Integer ',
                'total_worker_limit' => '60',
                'cost_per_worker' => '5.00',
                'task_end_date' => '2026-08-06',
                'special_access' => 'false',
                'only_professional' => 'true',
                'daily_limit' => '6',
                'task_cost' => '300.00',
                'other_cost' => '5.00',
                'total_cost' => '305.00',
                'publish_status' => 'Published',
            ],
            [
                'task_number' => 'T-Y-M-S-RCH-RNUM10',
                'category_id' => 10,
                'title' => 'Task number 10',
                'description' => 'Lorem ipsum dolor sit amet, cona aliqua.',
                'employer_id' => 10,
                'proof_request_ques' => 'here is no one who loves pain itself, who seeks after it and',
                'proof_request_screenShot' => 'mply because it is pain..',
                'total_worker_limit' => '78',
                'cost_per_worker' => '4.54',
                'task_end_date' => '2026-10-05',
                'special_access' => 'false',
                'only_professional' => 'true',
                'daily_limit' => '32',
                'task_cost' => '354.12',
                'other_cost' => '453.43',
                'total_cost' => '807.55',
                'publish_status' => 'Published',
            ],

        ];
        foreach ($tasks as $task){
            Task::create($task);
        }
    }
}
